[build]
  publish = "dist/mulume"
  command = "npm run build"
  environment = { BASE_URL = "/:lang" }

[[headers]]
  for = "/*"
    [headers.values]
      X-Frame-Options = "DENY"
      X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/:lang/*"
  to = "/:lang/index.html"
  status = 200
