[build]
  publish = "dist/mulume"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[headers."/*"]
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:"
