[build]
  publish = "dist/mulume"

[headers."/*"]
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:"

[[redirects]]
  from = "/:lang/*"
  to = "/:lang/index.html"
  status = 200
