# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: mulume CI/CD

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: ci # will run `yarn ci` command

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: Test the application
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn test` command
